name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Adjust to your Node.js version

      - name: Install Dependencies
        run: |
          npm install
          npm install three postprocessing  # Install Three.js and Postprocessing
        working-directory: ./  # Specify your project's directory if needed

      - name: Build Project
        run: npm run build
        working-directory: ./  # Specify your project's directory if needed

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Specify your build output directory
          publish_branch: gh-pages  # You can change this if needed
